#!/bin/bash

HOMEBREW_NO_AUTO_UPDATE=1

# 如果没有,那么增加一个进入.zshrc和环境变量中去! - 顺序很重要!
if ! grep "$HOME/bin:/opt/local/bin:\$PATH" ~/.zshrc; 
then
  echo "export PATH=\"$HOME/bin:/opt/local/bin:\$PATH\"" >> ~/.zshrc
fi

echo "即将开始安装PHP开发环境和MySql,Redis,Nginx:"

# 安装mysql
read -p "即将安装:mysql [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 MySql软件"
  #sudo port install mysql #用port安装太慢,还不方便,我们改回使用brew install 
  brew install mysql
  # 启动服务
  echo "brew 操作mysql的详细信息: brew info mysql"
  echo "启动mysql服务: brew services start mysql"
  echo "停止mysql服务: brew services start mysql"
fi

echo "---------------------------------------------"
# 安装redis
read -p "即将安装:redis [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 redis软件"
  #sudo port install redis #用port安装太慢,还不方便,我们改回使用brew install 
  brew install redis
  # 启动服务
  echo "brew 操作redis的详细信息: brew info redis"
  echo "启动redis服务: brew services start redis"
  echo "停止redis服务: brew services start redis"
fi

echo "---------------------------------------------"
# 安装nginx
read -p "即将安装:nginx [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 nginx软件"
  #sudo port install nginx #用port安装太慢,还不方便,我们改回使用brew install 
  brew install nginx

  # 安装配置文件 80端口监听需要root权限
  cp configs/nginx/nginx.conf /usr/local/etc/nginx/nginx.conf
  # 启动服务
  echo "brew 操作Nginx的详细信息: brew info nginx"
  echo "启动Nginx服务: sudo brew services start nginx"
  echo "停止Nginx服务: sudo brew services start nginx"
fi


# 安装各种版本php....!(因为最近brew安装php总出现各种奇怪问题,旧版本php brew又不在维护.所以只能暂时使用这个port来安装管理.)
echo "---------------------------------------------"
# 安装php54
read -p "即将安装:php5.4 [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 php5.4"
  sudo port install php54-fpm
  echo "安装php模块: php54-redis php54-imagick php54-intl php54-opcache php54-iconv php54-mysql php54-openssl php54-curl php54-mbstring php54-exif php54-pcntl php54-sockets php54-ftp php54-zip php54-soap"
  sudo port install php54-redis php54-imagick php54-intl php54-opcache php54-iconv php54-mysql php54-openssl php54-curl php54-mbstring php54-exif php54-pcntl php54-sockets php54-ftp php54-zip php54-soap
  # 修改配置文件 /opt/local/etc/php54
  sed -i '' "s/user\ \=\ _nobody/user\ \=\ $USER/g" configs/php/php54/php-fpm.conf
  sudo cp -r $PWD/configs/php/php54/ /opt/local/etc/php54/
  # 服务启动..
  echo "服务管理详细信息,详见: port help"
  echo "启动php-fpm服务: sudo port load php54-fpm"
  echo "停止php-fpm服务: sudo port unload php54-fpm"
  # 版本切换???
fi

echo "---------------------------------------------"
# 安装redis
read -p "即将安装:php7.0 [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 php7.0"
  sudo port install php70-fpm
  echo "安装php模块: php70-redis php70-imagick php70-intl php70-opcache php70-iconv php70-mysql php70-openssl php70-curl php70-mbstring php70-exif php70-pcntl php70-sockets php70-ftp php70-zip php70-soap"
  sudo port install php70-redis php70-imagick php70-intl php70-opcache php70-iconv php70-mysql php70-openssl php70-curl php70-mbstring php70-exif php70-pcntl php70-sockets php70-ftp php70-zip php70-soap
  # 修改配置文件 /opt/local/etc/php70
  sed -i '' "s/user\ \=\ _nobody/user\ \=\ $USER/g" configs/php/php70/php-fpm.d/www.conf
  sudo cp -r $PWD/configs/php/php70/ /opt/local/etc/php70/
  # 服务启动..
  echo "服务管理详细信息,详见: port help"
  echo "启动php-fpm服务: sudo port load php70-fpm"
  echo "停止php-fpm服务: sudo port unload php70-fpm"
  # 版本切换???
fi

echo "---------------------------------------------"
# 安装redis
read -p "即将安装:php7.2 [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 php7.2"
  sudo port install php72-fpm
  echo "安装php模块: php72-redis php72-imagick php72-intl php72-opcache php72-iconv php72-mysql php72-openssl php72-curl php72-mbstring php72-exif php72-pcntl php72-sockets php72-ftp php72-zip php72-soap"
  sudo port install php72-redis php72-imagick php72-intl php72-opcache php72-iconv php72-mysql php72-openssl php72-curl php72-mbstring php72-exif php72-pcntl php72-sockets php72-ftp php72-zip php72-soap
  # 修改配置文件 /opt/local/etc/php72 , 处理下执行权限
  sed -i '' "s/user\ \=\ _nobody/user\ \=\ $USER/g" configs/php/php72/php-fpm.d/www.conf
  sudo cp -r $PWD/configs/php/php72/ /opt/local/etc/php72/
  # 服务启动..
  echo "服务管理详细信息,详见: port help"
  echo "启动php-fpm服务: sudo port load php72-fpm"
  echo "停止php-fpm服务: sudo port unload php72-fpm"
fi

echo "---------------------------------------------"
# 安装 php-version命令,切换php版本
read -p "即将安装:php-version命令 [Y/n](默认为y)" IS_INSTALL
if [ "$IS_INSTALL" == "y" ] || [ "$IS_INSTALL" == "" ]
then
  echo "开始安装 php-version"
  if [ ! -d $HOME/bin ]
  then 
    mkdir $HOME/bin
  fi
  cp ./php-version $HOME/bin/
  
  echo "安装完成,执行 php-version 查看版本. php-version 5.4 切换版本."
fi

echo "-----------------------------------------------"

echo "安裝composer:"
composer -v
if  [ `echo $?` -ne 0 ] 
then
  php composer-setup.php --install-dir=bin --filename=composer
else
  echo "composer 安装完成!"
fi

